### ISSUE TITLE
AttributeError: function 'SetupDiGetDevicePropertyW' not found

### ISSUE THREAD

**Issue by boonestars** [Infinidat/infi.devicemanager#3]
In calling dm.root.rescan() i get the following AttributeError. Below is the full error.

>>> dm.root.rescan()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\infi\devicemanager\__init__.py", line 163, in rescan
    if not self.is_real_device():
  File "C:\Python27\lib\site-packages\infi\devicemanager\__init__.py", line 138, in is_real_device
    return self.has_property("location")
  File "C:\Python27\lib\site-packages\infi\devicemanager\__init__.py", line 145, in has_property
    _ = getattr(self, name)
  File "C:\Python27\lib\site-packages\infi\pyutils\lazy.py", line 86, in callee
    value = func(inst, *args, **kwargs)
  File "C:\Python27\lib\site-packages\infi\devicemanager\__init__.py", line 90, in location
    return self._get_setupapi_property(properties.DEVPKEY_Device_LocationInfo)
  File "C:\Python27\lib\site-packages\infi\devicemanager\__init__.py", line 39, in _get_setupapi_property
    return functions.SetupDiGetDeviceProperty(dis, devinfo, key).python_object
  File "C:\Python27\lib\site-packages\infi\devicemanager\setupapi\functions.py", line 102, in SetupDiGetDeviceProperty
    0, 0, byref(required_size), 0)
  File "C:\Python27\lib\site-packages\infi\cwrap\__init__.py", line 137, in __new__
    function = cls._get_function()
  File "C:\Python27\lib\site-packages\infi\cwrap\__init__.py", line 145, in _get_function
    cls.return_value, parameters, cls.get_errcheck())
  File "C:\Python27\lib\site-packages\infi\cwrap\__init__.py", line 74, in wrap_library_function
    _function = function_prototype((name, library), _paramflags)
AttributeError: function 'SetupDiGetDevicePropertyW' not found

**Comment by wiggin15** [comment]
What version of Windows are you using? SetupDiGetDeviceProperty is supported in Windows Vista and up. devicemanager supports the same.

**Comment by boonestars** [comment]
Ahh I didn't see that disclaimer, it was win xp. Thanks

**Comment by wiggin15** [comment]
I updated the README with this information.
We don't plan to add support for earlier versions of Windows.

**Comment by boonestars** [comment]
Thanks, I'm looking forward to trying it on my > Vista machines. I
definitely need something for xp so I'm going to try to find a way to do it
through the event log manager. Not sure if I will be able to get that to
work, or if you would be interested but an event for me is just as good as
a real time check.
