### ISSUE TITLE
dm.root.rescan() - raise OSError

### ISSUE THREAD

**Issue by drrest** [Infinidat/infi.devicemanager#6]
Ask me please, what i do wrong (( ?

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python2.7/dist-packages/infi/devicemanager/__init__.py", line 167, in rescan
        if not self.is_real_device() and not self.is_iscsi_device():
      File "/usr/local/lib/python2.7/dist-packages/infi/devicemanager/__init__.py", line 139, in is_real_device
        return self.has_property("location")
      File "/usr/local/lib/python2.7/dist-packages/infi/devicemanager/__init__.py", line 149, in has_property
        _ = getattr(self, name)
      File "/usr/local/lib/python2.7/dist-packages/infi/pyutils/lazy.py", line 86, in callee
        value = func(inst, *args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/infi/devicemanager/__init__.py", line 91, in location
        return self._get_setupapi_property(properties.DEVPKEY_Device_LocationInfo)
      File "/usr/local/lib/python2.7/dist-packages/infi/devicemanager/__init__.py", line 37, in _get_setupapi_property
        with self._open_handle() as handle:
      File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
        return self.gen.next()
      File "/usr/local/lib/python2.7/dist-packages/infi/devicemanager/__init__.py", line 28, in _open_handle
        dis = functions.SetupDiCreateDeviceInfoList()
      File "/usr/local/lib/python2.7/dist-packages/infi/devicemanager/setupapi/functions.py", line 130, in SetupDiCreateDeviceInfoList
        return interface(guid_buffer, 0)
      File "/usr/local/lib/python2.7/dist-packages/infi/cwrap/__init__.py", line 137, in __new__
        function = cls._get_function()
      File "/usr/local/lib/python2.7/dist-packages/infi/cwrap/__init__.py", line 144, in _get_function
        function = wrap_library_function(cls.__name__, cls._get_library(), cls._get_function_type(), 
      File "/usr/local/lib/python2.7/dist-packages/infi/cwrap/__init__.py", line 133, in _get_library
        raise OSError
    OSError

**Comment by wiggin15** [comment]
Hi there.
It appears that the line "ctypes.windll.setupapi", which should load setupapi.dll, fails on your system.
What operating system are you using?  Can you please try to run this code and paste the output:

    import ctypes
    ctypes.windll.setupapi

**Comment by amito** [comment]
Issue has been resolved in commits f28e6c65b54244986af431e03ad9e62e0600de4c and b5c4717794bc190d42e5259f8e85e715aeaba0b2.
