### ISSUE TITLE
Issue with versions after infi.devicemanager-0.2.16

### ISSUE THREAD

**Issue by anagramrice** [Infinidat/infi.devicemanager#7]
i updated the package recently but then had to roll it back to infi.devicemanager-0.2.16
Traceback (most recent call last):
  File "C:\Users\HPwifieasy\Desktop\Chamber1Utils\client_MainPCmodules\serialMon\serialLogger.py", line 145, in <module>
    new = SerialLogger()
  File "C:\Users\HPwifieasy\Desktop\Chamber1Utils\client_MainPCmodules\serialMon\serialLogger.py", line 22, in __init__
    self.createUSBclassInfo()
  File "C:\Users\HPwifieasy\Desktop\Chamber1Utils\client_MainPCmodules\serialMon\serialLogger.py", line 45, in createUSBclassInfo
    dm.root.rescan()
  File "C:\Python27\lib\site-packages\infi\devicemanager\__init__.py", line 167, in rescan
    if not self.is_real_device() and not self.is_iscsi_device():
  File "C:\Python27\lib\site-packages\infi\devicemanager\__init__.py", line 142, in is_iscsi_device
    return any("iSCSI" in hardware_id for hardware_id in self.hardware_ids)
  File "C:\Python27\lib\site-packages\infi\pyutils\lazy.py", line 86, in callee
    value = func(inst, *args, **kwargs)
  File "C:\Python27\lib\site-packages\infi\devicemanager\__init__.py", line 63, in hardware_ids
    return self._get_setupapi_property(properties.DEVPKEY_Device_HardwareIds)
  File "C:\Python27\lib\site-packages\infi\devicemanager\__init__.py", line 43, in _get_setupapi_property
    raise KeyError(key)
KeyError: DEVPROPKEY(Data1=2757502286, Data2=57116, Data3=20221, Data4=[ 128, 32, 103, 209, 70, 168, 80, 224 ], pid=3)

**Comment by bobquest33** [comment]
Hi I also ended up getting the same error when I run it in Python 3.6. Can you please help to highlight the specific reason for this error.

**Comment by Apuyuseng** [comment]
run dome get error `\site-packages\infi\devicemanager\__init__.py", line 43, in _get_setupapi_property
    raise KeyError(key)
KeyError: DEVPROPKEY(Data1=2757502286, Data2=57116, Data3=20221, Data4=[ 128, 32, 103, 209, 70, 168, 80, 224 ], pid=3)`

**Comment by amito** [comment]
Issue has been resolved in commits f28e6c65b54244986af431e03ad9e62e0600de4c and b5c4717794bc190d42e5259f8e85e715aeaba0b2.

**Comment by SUSHMITAH** [comment]
Hi,
I am new to Github...To resolve the above error should what files should be modified using the commits f28e6c6 and b5c4717?

**Comment by amito** [comment]
Hi @SUSHMITAH. To get the most updated code with a resolution to the above error, simply use the latest stable version of the code (v0.2.21).
